CrudPersona/Models/ErrorViewModel.cs
namespace CrudPersona.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CrudPersona/Models/PersonaViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CrudPersona.Models
{
    public class PersonaViewModel
    {
        public int Id { get; set; }

        public string Nombre { get; set; } = string.Empty;

        [DataType(DataType.Date)]
        public DateTime FechaDeNacimiento { get; set; }
    }
}

CrudPersona/Controllers/HomeController.cs
using CrudPersona.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CrudPersona.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CrudPersona/Controllers/PersonaController.cs
using CrudPersona.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace CrudPersona.Controllers
{
    public class PersonaController : Controller
    {
        Uri baseAddress = new Uri("http://www.pruebanaomi.somee.com/api");
        HttpClient client;

        public PersonaController()
        {
            client = new HttpClient();
            client.BaseAddress = baseAddress;
        }
        public async Task<ActionResult> Index()
        {
            List<PersonaViewModel> modelList = new List<PersonaViewModel>();
            HttpResponseMessage response = client.GetAsync(client.BaseAddress + "/personas").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                modelList = JsonConvert.DeserializeObject<List<PersonaViewModel>>(data);
            }
            return View(modelList);
        }

        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Crear(PersonaViewModel model)
        {
            string data = JsonConvert.SerializeObject(model);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");

            HttpResponseMessage response = client.PostAsync(client.BaseAddress + "/personas", content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Borrar(int id)
        {
            HttpResponseMessage response = client.DeleteAsync(client.BaseAddress + "/personas/" + id).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

CrudPersona/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about me <a href="https://naeliza.netlify.app/#home">Naeliza</a>.</p>
</div>

CrudPersona/Views/Persona/Crear.cshtml
@model CrudPersona.Models.PersonaViewModel

@{
    ViewBag.Title = "Crear";
}

<h1>@ViewBag.Title</h1>
<hr />
@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Crear()">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                @Html.HiddenFor(model => model.Id)
                <div class="form-group mb-3">
                    <label asp-for="Nombre" class="control-label"></label>
                    <input asp-for="Nombre" class="form-control" type="text" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="FechaDeNacimiento" class="control-label">Fecha De Nacimiento</label>
                    <input asp-for="FechaDeNacimiento" class="form-control" type="date" />
                    <span asp-validation-for="FechaDeNacimiento" class="text-danger"></span>
                </div>
                <div class="form-group mt-5">
                    <input type="submit" value="Grabar" class="btn btn-outline-secondary" />
                </div>
            </form>
        </div>
    </div>
}

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

CrudPersona/Views/Persona/Index.cshtml
@model IEnumerable<CrudPersona.Models.PersonaViewModel>

@{
    ViewData["Title"] = "Crud Persona";
}


<h3>Crud Persona made with ASP.net Core By Naeliza</h3>
<hr />
</br>

<p>
    <a asp-action="Crear" class="btn btn-outline-secondary">Añadir nueva persona</a>
</p>

<table class="table table-hover">
    <thead>
        <tr class="table-primary">
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaDeNacimiento)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaDeNacimiento)
                </td>
                <td>
                    @Html.ActionLink("Borrar", "Borrar", new { id=item.Id  }, new {@class="btn btn-outline-secondary"})
                </td>
            </tr>
        }
    </tbody>
</table>

CrudPersona/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudPersona</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrudPersona.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Persona" asp-action="Index">CrudPersona</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                           
                        </li>
                        <li class="nav-item">
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CrudPersona - <a asp-area="" asp-controller="Home" >Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>